version: "3.9"

services:
  frontend:
    container_name: next_gallery_frontend_container
    build: ./next-gallery
    ports:
      - "5173:5173"
    env_file:
      - ./.env    
    depends_on:
      - backend
    tty: true
    command: npm run dev

  backend:
    container_name: next_gallery_backend_container
    build: ./next-gallery-backend
    ports:
      - "3001:3001"
    env_file:
      - ./.env     
    volumes:
      - ./next-gallery-backend/uploads:/app/uploads
    tty: true
    command: npm run dev
